# Generated by Django 5.0.3 on 2024-05-22 02:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Product', '0001_initial'),
        ('Restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products_restaurant',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Restaurant.restaurant'),
        ),
    ]
