# Generated by Django 5.0.3 on 2024-05-22 03:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant', '0002_initial'),
        ('User', '0002_waiter_shift_restaurant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_restaurant', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Restaurant.tables_restaurant')),
                ('waiter', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='User.waiter')),
            ],
        ),
    ]
