# Generated by Django 5.0.3 on 2024-05-22 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0002_initial'),
        ('Restaurant', '0003_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products_Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Restaurant.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Product.product')),
            ],
        ),
    ]
