# Generated by Django 5.0.3 on 2024-05-22 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant', '0005_bill'),
        ('User', '0002_waiter_shift_restaurant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tip_Waiter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid', models.BooleanField(default=False)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Restaurant.bill')),
                ('waiter', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='User.waiter')),
            ],
        ),
    ]
