# Generated by Django 5.0.3 on 2024-05-22 02:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant', '0002_initial'),
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='waiter_shift',
            name='restaurant',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='Restaurant.restaurant'),
        ),
    ]
